### ISSUE TITLE
Database automagically updating.

### ISSUE THREAD

**Issue by Elthan** [Elthan/LeagueofItemSets#19]

**Comment by Chorcon** [comment]
Automatically.. Nice!

**Comment by Elthan** [comment]
Takk :p
Fortsatt usikker på hvordan vi skal legge opp dette, noen tips?

**Comment by Chorcon** [comment]
Jeg tror django har en feature for gjentakende oppgaver. Kan sjekke ut litt
:)
18. aug. 2015 16.49 skrev "Jonas" <notifications@github.com>:

**Comment by Elthan** [comment]
This has to be a cron job or similar.
